AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'test/*'

Metrics/BlockLength:
  Exclude:
    - 'test/*'

Style/NilComparison:
  Exclude:
    - 'test/*'
