version: '3'

services:

  corelib-ruby:
    container_name: 'corelib-ruby'
    build:
      context: ./ruby
    environment:
      - DB_HOST=corelib-database
      - DB_USER=corelib
      - DB_PASSWORD=corelib
      - DB_DBNAME=corelib
      - CACHE_HOST=corelib-cache
      - CACHE_PORT=11211
      - MAILER_METHOD=logger
      - QUEUE_HOST=corelib-queue
      - QUEUE_PORT=11300
      - SEARCH_HOST=corelib-search
    volumes:
      - ../:/code
    depends_on:
      - corelib-database
      - corelib-cache
      - corelib-queue
      - corelib-search
    networks:
      corelib-net:

  corelib-database:
    container_name: 'corelib-database'
    image: postgres:10
    environment:
        - POSTGRES_USER=corelib
        - POSTGRES_PASSWORD=corelib
        - POSTGRES_DB=corelib
    volumes:
        - ./database:/docker-entrypoint-initdb.d
    networks:
      corelib-net:

  corelib-cache:
    container_name: 'corelib-cache'
    image: memcached:alpine
    networks:
      corelib-net:

  corelib-queue:
    container_name: 'corelib-queue'
    image: schickling/beanstalkd
    networks:
      corelib-net:

  corelib-search:
    container_name: 'corelib-search'
    image: elasticsearch:alpine
    networks:
      corelib-net:

networks:
  corelib-net:
